# Perfil de DESARROLLO LOCAL: SPRING_PROFILES_ACTIVE=dev

# SQL visible para depurar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DevTools ya se activa solo en classpath de desarrollo.
