# Perfil de PRODUCCION (default si no se define SPRING_PROFILES_ACTIVE)

# Nunca loguear SQL en produccion
spring.jpa.show-sql=false

# Logging sobrio
logging.level.org.hibernate.SQL=WARN
logging.level.com.tuusuario.employee_time_tracker=INFO
