-- Esquema base para H2 (solo tests de integracion).

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    pin_hash VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20),
    employee_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_employee UNIQUE (employee_id),
    CONSTRAINT fk_users_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE time_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    clock_in TIMESTAMP(6),
    clock_out TIMESTAMP(6),
    status VARCHAR(255) CHECK (status IN ('CLOCKED_IN','ON_BREAK','FINISHED')),
    auto_closed BOOLEAN,
    employee_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_time_entries_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE break_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    break_start TIMESTAMP(6),
    break_end TIMESTAMP(6),
    break_status VARCHAR(255) CHECK (break_status IN ('ON_BREAK','FINISHED')),
    duration BIGINT,
    time_entry_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_break_entries_time_entry FOREIGN KEY (time_entry_id) REFERENCES time_entries (id)
);
